CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  email TEXT,
  phone TEXT NOT NULL,
  address TEXT NOT NULL,
  product TEXT NOT NULL,
  size TEXT NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  total INTEGER NOT NULL CHECK (total > 0),
  status TEXT NOT NULL DEFAULT 'Pending Confirmation',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.orders TO service_role;

CREATE OR REPLACE FUNCTION public.sync_orders_id_sequence()
RETURNS VOID
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT setval(
    pg_get_serial_sequence('public.orders', 'id'),
    COALESCE(MAX(id), 1),
    MAX(id) IS NOT NULL
  )
  FROM public.orders;
$$;

REVOKE ALL ON FUNCTION public.sync_orders_id_sequence() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sync_orders_id_sequence() TO service_role;
